#!/bin/bash

if [ -f ".dotfiles_env" ]; then
  echo ".dotfiles_env exists."
  echo "Continuing..."
else
  echo ".dotfiles_env does not exists."
  echo "copying from dotfiles_env_sample"
  cp dotfiles_env_sample .dotfiles_env
fi

if [[ ! -e .tmp_env ]]; then
  touch .tmp_env
  echo "#export FOO=\"bar bar ra\"" >> .tmp_env 
fi

dotfiles=(".tmp_env" ".tmux.conf" ".zshrc" ".aliases" ".functions" ".dotfiles_env")
dir="${HOME}/.dotfiles"

for dotfile in "${dotfiles[@]}";do 
  if [ -f "${HOME}/${dotfile}" ]; then
    rm "${HOME}/${dotfile}"
    ln -s "${dir}/${dotfile}" "${HOME}"
  else
    ln -s "${dir}/${dotfile}" "${HOME}"
  fi
done

echo "if [[ ! \$TERM =~ screen ]]; then
    exec tmux
fi" >> "$HOME/.bashrc"

echo "Dotfiles installed successfully"
