#!/bin/bash

dotfiles=(".tmux.conf" ".zshrc" ".aliases")
dir="${HOME}/.dotfiles"

for dotfile in "${dotfiles[@]}";do 
  if [ -f "${HOME}/${dotfile}" ]; then
    rm "${HOME}/${dotfile}"
    ln -s "${dir}/${dotfile}" "${HOME}"
  else
    ln -s "${dir}/${dotfile}" "${HOME}"
  fi
done

source ~/.zshrc
echo "Dotfiles installed successfully"
