#!/bin/bash

dotfiles=(".tmux.conf" ".zshrc" ".aliases" ".functions" ".dotfiles_env")
dir="${HOME}/.dotfiles"

for dotfile in "${dotfiles[@]}";do 
  if [ -f "${HOME}/${dotfile}" ]; then
    rm "${HOME}/${dotfile}"
  else
    echo "${HOME}/${dotfile} not found" 
  fi
done

echo "Dotfiles uninstalled successfully"
