#!/bin/bash

dotfiles=(".tmp_env" ".tmux.conf" ".zshrc" ".aliases" ".functions" ".dotfiles_env")
dir="${HOME}/.dotfiles"

echo "dont execute this from the .dotfiles directory"

for dotfile in "${dotfiles[@]}";do 
  if [ -f "${HOME}/${dotfile}" ]; then
    rm "${HOME}/${dotfile}"
  else
    echo "${HOME}/${dotfile} not found" 
  fi
done

sed '/$TERM =~ screen/,+2d' "$HOME/.bashrc" >> "$HOME/.bashrc"

cd ..
rm -rf "$HOME/.dotfiles"

echo "Dotfiles uninstalled successfully"
